# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogIn():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_logIn(self):
    # Test name: Log In
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://192.168.1.64:6070/")
    # 2 | setWindowSize | 974x1080 | 
    self.driver.set_window_size(974, 1080)
    # 3 | click | css=.btn:nth-child(1) > .flex | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1) > .flex").click()
    # 4 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 5 | type | name=username | Eco
    self.driver.find_element(By.NAME, "username").send_keys("Eco")
    # 6 | type | name=password | 123
    self.driver.find_element(By.NAME, "password").send_keys("123")
    # 7 | waitForElementVisible | css=.login100-form-btn | 123
    WebDriverWait(self.driver, 0.123).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".login100-form-btn")))
    # 8 | click | css=.login100-form-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".login100-form-btn").click()
    # 9 | click | name=code | 
    self.driver.find_element(By.NAME, "code").click()
    # 10 | type | name=code | 999020
    self.driver.find_element(By.NAME, "code").send_keys("999020")
    # 11 | sendKeys | name=code | ${KEY_ENTER}
    self.driver.find_element(By.NAME, "code").send_keys(Keys.ENTER)
  
