# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWithdraw():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_withdraw(self):
    # Test name: Withdraw
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://192.168.1.64:6070/")
    # 2 | setWindowSize | 1920x1080 | 
    self.driver.set_window_size(1920, 1080)
    # 3 | click | css=.btn:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    # 4 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 5 | type | name=username | Eco
    self.driver.find_element(By.NAME, "username").send_keys("Eco")
    # 6 | type | name=password | 123
    self.driver.find_element(By.NAME, "password").send_keys("123")
    # 7 | click | css=.login100-form-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".login100-form-btn").click()
    # 8 | click | name=code | 
    self.driver.find_element(By.NAME, "code").click()
    # 9 | type | name=code | 371020
    self.driver.find_element(By.NAME, "code").send_keys("371020")
    # 10 | click | css=.login100-form-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".login100-form-btn").click()
    # 11 | click | css=.checkbox | 
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox").click()
    # 12 | click | id=withdrawl-button | 
    self.driver.find_element(By.ID, "withdrawl-button").click()
    # 13 | click | id=coin-withdrawl | 
    self.driver.find_element(By.ID, "coin-withdrawl").click()
    # 14 | type | id=coin-withdrawl | 0.02
    self.driver.find_element(By.ID, "coin-withdrawl").send_keys("0.02")
    # 15 | click | id=amount-withdrawl | 
    self.driver.find_element(By.ID, "amount-withdrawl").click()
    # 16 | type | id=amount-withdrawl | 12
    self.driver.find_element(By.ID, "amount-withdrawl").send_keys("12")
    # 17 | click | css=#withdrawl-form > button | 
    self.driver.find_element(By.CSS_SELECTOR, "#withdrawl-form > button").click()
    # 18 | click | css=.checkbox | 
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox").click()
    # 19 | click | id=withdrawl-button | 
    self.driver.find_element(By.ID, "withdrawl-button").click()
    # 20 | click | id=coin-withdrawl | 
    self.driver.find_element(By.ID, "coin-withdrawl").click()
    # 21 | type | id=coin-withdrawl | 0.02
    self.driver.find_element(By.ID, "coin-withdrawl").send_keys("0.02")
    # 22 | click | id=amount-withdrawl | 
    self.driver.find_element(By.ID, "amount-withdrawl").click()
    # 23 | type | id=amount-withdrawl | 101
    self.driver.find_element(By.ID, "amount-withdrawl").send_keys("101")
    # 24 | click | css=#withdrawl-form > button | 
    self.driver.find_element(By.CSS_SELECTOR, "#withdrawl-form > button").click()
    # 25 | click | css=.checkbox | 
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox").click()
    # 26 | click | id=withdrawl-button | 
    self.driver.find_element(By.ID, "withdrawl-button").click()
    # 27 | click | id=coin-withdrawl | 
    self.driver.find_element(By.ID, "coin-withdrawl").click()
    # 28 | click | id=coin-withdrawl | 
    self.driver.find_element(By.ID, "coin-withdrawl").click()
    # 29 | click | id=coin-withdrawl | 
    self.driver.find_element(By.ID, "coin-withdrawl").click()
    # 30 | type | id=coin-withdrawl | 100
    self.driver.find_element(By.ID, "coin-withdrawl").send_keys("100")
    # 31 | click | id=amount-withdrawl | 
    self.driver.find_element(By.ID, "amount-withdrawl").click()
    # 32 | type | id=amount-withdrawl | 0.1
    self.driver.find_element(By.ID, "amount-withdrawl").send_keys("0.1")
    # 33 | sendKeys | id=amount-withdrawl | ${KEY_ENTER}
    self.driver.find_element(By.ID, "amount-withdrawl").send_keys(Keys.ENTER)
    # 34 | type | id=amount-withdrawl | 1
    self.driver.find_element(By.ID, "amount-withdrawl").send_keys("1")
    # 35 | click | css=#withdrawl-form > button | 
    self.driver.find_element(By.CSS_SELECTOR, "#withdrawl-form > button").click()
  
