# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStatement():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_statement(self):
    # Test name: Statement
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://192.168.1.64:6070/")
    # 2 | setWindowSize | 1920x1080 | 
    self.driver.set_window_size(1920, 1080)
    # 3 | click | css=.w-90 | 
    self.driver.find_element(By.CSS_SELECTOR, ".w-90").click()
    # 4 | click | css=.btn:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    # 5 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 6 | type | name=username | Eco
    self.driver.find_element(By.NAME, "username").send_keys("Eco")
    # 7 | type | name=password | 123
    self.driver.find_element(By.NAME, "password").send_keys("123")
    # 8 | click | css=.login100-form-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".login100-form-btn").click()
    # 9 | click | name=code | 
    self.driver.find_element(By.NAME, "code").click()
    # 10 | type | name=code | 140116
    self.driver.find_element(By.NAME, "code").send_keys("140116")
    # 11 | click | css=.login100-form-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".login100-form-btn").click()
    # 12 | click | css=.checkbox | 
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox").click()
    # 13 | click | linkText=Statement | 
    self.driver.find_element(By.LINK_TEXT, "Statement").click()
    # 14 | click | id=file-label | 
    self.driver.find_element(By.ID, "file-label").click()
    # 15 | type | id=file | C:\Users\Tiago\OneDrive - Universidade de Aveiro\Desktop\Tiago\2 Ano\AS\AS\Projeto\Project-ECO\tests\descarga.xls
    self.driver.find_element(By.ID, "file").send_keys("C:\\Users\\Tiago\\OneDrive - Universidade de Aveiro\\Desktop\\Tiago\\2 Ano\\AS\\AS\\Projeto\\Project-ECO\\tests\\descarga.xls")
    # 16 | click | css=input:nth-child(9) | 
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    # 17 | click | linkText=Ver Despesas | 
    self.driver.find_element(By.LINK_TEXT, "Ver Despesas").click()
    # 18 | open | /statement/Eco | 
    self.driver.get("http://192.168.1.64:6070/statement/Eco")
    # 19 | click | linkText=Ver Receitas | 
    self.driver.find_element(By.LINK_TEXT, "Ver Receitas").click()
    # 20 | open | /statement/Eco | 
    self.driver.get("http://192.168.1.64:6070/statement/Eco")
    # 21 | click | linkText=Baixar Relatório Económico | 
    self.driver.find_element(By.LINK_TEXT, "Baixar Relatório Económico").click()
    # 22 | open | /statement/Eco | 
    self.driver.get("http://192.168.1.64:6070/statement/Eco")
    # 23 | click | linkText=Baixar Extrato ECO | 
    self.driver.find_element(By.LINK_TEXT, "Baixar Extrato ECO").click()
  
