# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAccountSettings():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_accountSettings(self):
    # Test name: Account Settings
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://192.168.1.64:6070/")
    # 2 | setWindowSize | 1920x1080 | 
    self.driver.set_window_size(1920, 1080)
    # 3 | click | css=.btn:nth-child(1) > .flex | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1) > .flex").click()
    # 4 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 5 | type | name=username | Eco
    self.driver.find_element(By.NAME, "username").send_keys("Eco")
    # 6 | type | name=password | 123
    self.driver.find_element(By.NAME, "password").send_keys("123")
    # 7 | click | css=.login100-form-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".login100-form-btn").click()
    # 8 | click | name=code | 
    self.driver.find_element(By.NAME, "code").click()
    # 9 | type | name=code | 410190
    self.driver.find_element(By.NAME, "code").send_keys("410190")
    # 10 | click | css=.login100-form-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".login100-form-btn").click()
    # 11 | click | css=.checkbox | 
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox").click()
    # 12 | click | css=.profile-img > img | 
    self.driver.find_element(By.CSS_SELECTOR, ".profile-img > img").click()
    # 13 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 14 | type | id=username | Eco_new
    self.driver.find_element(By.ID, "username").send_keys("Eco_new")
    # 15 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 16 | click | css=.container | 
    self.driver.find_element(By.CSS_SELECTOR, ".container").click()
    # 17 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 18 | type | id=email | tiago.s.fonseca2022@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("tiago.s.fonseca2022@gmail.com")
    # 19 | click | id=psw | 
    self.driver.find_element(By.ID, "psw").click()
    # 20 | type | id=psw | ola
    self.driver.find_element(By.ID, "psw").send_keys("ola")
    # 21 | click | id=psw-repeat | 
    self.driver.find_element(By.ID, "psw-repeat").click()
    # 22 | type | id=psw-repeat | ola
    self.driver.find_element(By.ID, "psw-repeat").send_keys("ola")
    # 23 | click | name=profile_photo | 
    self.driver.find_element(By.NAME, "profile_photo").click()
    # 24 | type | name=profile_photo | C:\Users\Tiago\OneDrive - Universidade de Aveiro\Desktop\Tiago\2 Ano\AS\AS\Projeto\Project-ECO\tests\test_image.png
    self.driver.find_element(By.NAME, "profile_photo").send_keys("C:\\Users\\Tiago\\OneDrive - Universidade de Aveiro\\Desktop\\Tiago\\2 Ano\\AS\\AS\\Projeto\\Project-ECO\\tests\\test_image.png")
    # 25 | click | css=.savebtn | 
    self.driver.find_element(By.CSS_SELECTOR, ".savebtn").click()
  
